"""add spaced repetition fields to words

Revision ID: 2309c3fdd52d
Revises: 5afd13a7fd38
Create Date: 2026-06-17 21:07:22.953341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2309c3fdd52d'
down_revision: Union[str, Sequence[str], None] = '5afd13a7fd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('difficulty', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('words', sa.Column('repetition_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('words', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'next_review_at')
    op.drop_column('words', 'repetition_level')
    op.drop_column('words', 'difficulty')
    # ### end Alembic commands ###
