"""add category_id to words

Revision ID: 4512142231ba
Revises: 5c80e136c216
Create Date: 2026-06-08 19:44:20.419774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4512142231ba'
down_revision: Union[str, Sequence[str], None] = '5c80e136c216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "words",
        sa.Column(
            "category_id",
            sa.String(),
            nullable=True
        )
    )

    op.create_foreign_key(
        None,
        "words",
        "categories",
        ["category_id"],
        ["id"]
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'category_id')
    # ### end Alembic commands ###
